### ISSUE TITLE
Doesn't work when I try to parse a chrome browser version

### ISSUE THREAD

**Issue by ayumi-cloud** [PHLAK/SemVer#20]
Take the following code:

```php
use PHLAK\SemVer;

$version = new SemVer\Version('89.0.4373.1');

echo $version.'<br>';             // '89.0.4373.1'
echo $version->major.'<br>';      // 89
echo $version->minor.'<br>';      // 0
echo $version->patch.'<br>';      // 4373
echo $version->preRelease;        // 1
```

Note: `89.0.4373.1` is current Chrome version I'm using.

Comes back saying this:

```
PHLAK\SemVer\Exceptions\InvalidVersionException: Invalid Semantic Version string provided in /vendor/phlak/semver/src/Version.php:113
```

**Comment by PHLAK** [comment]
The version string `89.0.4373.1` does not adhere to the [semantic version specification](https://semver.org/#semantic-versioning-specification-semver) and is therefor an invalid semantic version string. This library only supports version strings that adhere to that spec. Therefor the exception you're seeing is the expected behavior in this case.

More specifically, see paragraph 9 of the specification where it says

> A pre-release version MAY be denoted by **appending a hyphen** and a series of dot separated identifiers immediately following the patch version.

To get the result you're expecting with a pre-release value of `1` the version would need to be `89.0.4373-1` (note the hyphen instead of the last period).

**Comment by ayumi-cloud** [comment]
@PHLAK Thank you, for a quick reply.
